add_test([=[Packet.HeaderSize]=]  /home/necdetsanli/udp-highrate/build-e2e/tests/unit_tests [==[--gtest_filter=Packet.HeaderSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Packet.HeaderSize]=]  PROPERTIES WORKING_DIRECTORY /home/necdetsanli/udp-highrate/build-e2e/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Packet.NowNsMonotonic]=]  /home/necdetsanli/udp-highrate/build-e2e/tests/unit_tests [==[--gtest_filter=Packet.NowNsMonotonic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Packet.NowNsMonotonic]=]  PROPERTIES WORKING_DIRECTORY /home/necdetsanli/udp-highrate/build-e2e/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Packet.HumanRate]=]  /home/necdetsanli/udp-highrate/build-e2e/tests/unit_tests [==[--gtest_filter=Packet.HumanRate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Packet.HumanRate]=]  PROPERTIES WORKING_DIRECTORY /home/necdetsanli/udp-highrate/build-e2e/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Stats.BasicCounters]=]  /home/necdetsanli/udp-highrate/build-e2e/tests/unit_tests [==[--gtest_filter=Stats.BasicCounters]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Stats.BasicCounters]=]  PROPERTIES WORKING_DIRECTORY /home/necdetsanli/udp-highrate/build-e2e/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Stats.Clients]=]  /home/necdetsanli/udp-highrate/build-e2e/tests/unit_tests [==[--gtest_filter=Stats.Clients]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Stats.Clients]=]  PROPERTIES WORKING_DIRECTORY /home/necdetsanli/udp-highrate/build-e2e/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MockSocket.SendAndRecv]=]  /home/necdetsanli/udp-highrate/build-e2e/tests/unit_tests [==[--gtest_filter=MockSocket.SendAndRecv]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MockSocket.SendAndRecv]=]  PROPERTIES WORKING_DIRECTORY /home/necdetsanli/udp-highrate/build-e2e/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Client.SendsSomething]=]  /home/necdetsanli/udp-highrate/build-e2e/tests/unit_tests [==[--gtest_filter=Client.SendsSomething]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Client.SendsSomething]=]  PROPERTIES WORKING_DIRECTORY /home/necdetsanli/udp-highrate/build-e2e/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Server.ReceivesAndEchoes]=]  /home/necdetsanli/udp-highrate/build-e2e/tests/unit_tests [==[--gtest_filter=Server.ReceivesAndEchoes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Server.ReceivesAndEchoes]=]  PROPERTIES WORKING_DIRECTORY /home/necdetsanli/udp-highrate/build-e2e/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  unit_tests_TESTS Packet.HeaderSize Packet.NowNsMonotonic Packet.HumanRate Stats.BasicCounters Stats.Clients MockSocket.SendAndRecv Client.SendsSomething Server.ReceivesAndEchoes)
